{% set name = "fvgp" %}
{% set version = "4.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lbl-camera/fvGP/archive/{{ version }}.tar.gz
  sha256: 4c8c4e561a33c560dce93c37cd9f24f43d53acaa6326dc3687c78f4737ee71d0
  patches:
    - dep.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - scipy =1.12.0
    - numpy =1.23.5
    - matplotlib-base
    - dask-core =2024.1.0
    - distributed =2024.1.0
    - hgdl =2.1.3
    - notebook
    - plotly
    - loguru

test:
  imports:
    - fvgp
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lbl-camera/fvGP
  summary: Python package for highly flexible function-valued Gaussian processes (fvGP)
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
