{% set name = "fvgp" %}
{% set version = "4.8.6" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fvgp-{{ version }}.tar.gz
  sha256: 37cfe90b5a0d028ac0c16e900065cf2b7036326c971fe27e26a714ad01e58eb3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - wheel
    - scipy >=1.13
    - numpy >=2.1
    - dask-core >=2024.1
    - distributed >=2024.1
    - hgdl >=2.2.3
    - loguru

test:
  imports:
    - fvgp
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lbl-camera/fvGP
  summary: Python package for highly flexible function-valued Gaussian processes (fvGP)
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
