{% set name = "fvgp" %}
{% set version = "4.7.7" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fvgp-{{ version }}.tar.gz
  sha256: 3a0bb4144573297a1376ddf7849a6d9458f9d03ed33ff69334a4b4a1a6faf8d0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - wheel
    - scipy >=1.16.0,<1.17.dev0
    - numpy >=2.2.6,<2.3.dev0
    - dask-core >=2025.5.1,<2025.6.dev0
    - distributed >=2025.5.1,<2025.6.dev0
    - hgdl >=2.3.1,<2.4.dev0
    - loguru

test:
  imports:
    - fvgp
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lbl-camera/fvGP
  summary: Python package for highly flexible function-valued Gaussian processes (fvGP)
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
