{% set name = "fvgp" %}
{% set version = "4.5.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fvgp-{{ version }}.tar.gz
  sha256: 961723b261614b0422ffae667fadace3fc5c84d0f40305473e11618fb486c4cf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - wheel
    - scipy >=1.13.0,<1.14.0
    - numpy >=2.1.1,<2.2.0
    - dask-core >=2024.1.0,<2024.2.0
    - distributed >=2024.1.0,<2024.2.0
    - hgdl >=2.2.1,<2.3.0   
    - loguru

test:
  imports:
    - fvgp
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lbl-camera/fvGP
  summary: Python package for highly flexible function-valued Gaussian processes (fvGP)
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
