{% set name = "fvgp" %}
{% set version = "7.4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lbl-camera/fvGP/archive/{{ version }}.tar.gz
  sha256: 994aa97ad476e91044dcdec835d770d9f3e91670d87fe978bf2ae3235f2ab82b
  patches:
    - dep.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pytorch >=1.9.0
    - scipy
    - numpy
    - matplotlib-base
    - dask-core >=2021.6.2
    - distributed >=2021.6.2
    - hgdl =2.0.7
    - notebook
    - plotly
    - loguru

test:
  imports:
    - fvgp
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lbl-camera/fvGP
  summary: Python package for highly flexible function-valued Gaussian processes (fvGP)
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
